///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();
  static const String imagesBooklyLogo = 'assets/images/BooklyLogo.png';
  static const String imagesLogo = 'assets/images/Logo.png';
  static const String imagesLogoText = 'assets/images/LogoText.png';
  static const String imagesSearchBook = 'assets/images/SearchBook.png';
  static const String imagesTestImage =
      'https://img.freepik.com/free-vector/red-text-book-closed-icon_18591-82397.jpg?t=st=1707730333~exp=1707730933~hmac=8b92bad7bc1679df532b44d7b3c9394aa4307daa64118363e09dc26a310ae3ca';
}
