///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();
  static const String imagesBooklyLogo = 'assets/images/BooklyLogo.png';
  static const String imagesLogo = 'assets/images/Logo.png';
  static const String imagesLogoText = 'assets/images/LogoText.png';
  static const String imagesSearchBook = 'assets/images/SearchBook.png';
  static const String imagesTestImage = 'assets/images/TestImage.png';
}
